# Generated by Django 3.0.2 on 2020-05-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
