# Generated by Django 3.0.2 on 2020-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvApp', '0002_auto_20200516_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
    ]
