# Generated by Django 3.0.2 on 2020-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvApp', '0003_remove_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Course', max_length=80),
        ),
    ]
