# Generated by Django 3.0.2 on 2020-05-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvApp', '0004_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
