# Generated by Django 3.0.2 on 2020-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvApp', '0005_auto_20200516_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
